spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/market?serverTimezone=Asia/Seoul"
    username: "root"
    password: "mysql"
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 6dNxE8lUwj2C=AukKrm9
  web:
    resources:
      cache:
        period: 0
        cachecontrol:
          no-store: true
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
      disable-swagger-default-url: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          readOnly: false
  main:
    allow-bean-definition-overriding: true

  session:
    store-type: redis

  redis:
    host:
      password:
        port : 6379

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

logging:
  level:
    org.springframework.security: DEBUG