spring:
  datasource:
    url: "jdbc:mysql://db:3306/market?serverTimezone=Asia/Seoul"
    username: "root"
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: http://elasticsearch:9200
  web:
    resources:
      cache:
        period: 0
        cachecontrol:
          no-store: true
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
    livereload:
      enabled: true
  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
      disable-swagger-default-url: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection:
          readOnly: false
  main:
    allow-bean-definition-overriding: true

  session:
    store-type: redis

  redis:
    host: redis
    port: 6379

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG